[versions]
## A
accessControlEntitlements = "10.0.0"
authentication = "10.0.0"

## B
bom = "2026.03.1-LTS"

## C
contacts-manager-journey = "9.1.0"

## F
featureFilter = "10.0.0"

## M
moreMenu = "9.0.0"

## W
workspaces = "10.1.0"

[libraries]
## A
accessControlEntitlementsUseCase = { group = "com.backbase.android.retail.feature_filter", name = "accesscontrol-client-2-entitlements-use-case", version.ref = "accessControlEntitlements" }
authentication-journey = { group = "com.backbase.android.identity.journey", name = "authentication-journey", version.ref = "authentication" }
authentication-use-case = { group = "com.backbase.android.identity.journey", name = "identity-auth-client-1-authentication-use-case", version.ref = "authentication" }

## B
bom = { module = "com.backbase:backbase-bom", version.ref = "bom" }
business-journey-common = { group = "com.backbase.android.business.journey", name = "journey-common", version = "" }

## C
clients-common-coroutines = { group = "com.backbase.android.clients", name = "clients-common-coroutines", version = "" }
contacts-manager-journey = { group = "com.backbase.android.business.journey", name = "contacts-manager-journey", version.ref = "contacts-manager-journey" }
contacts-manager-use-case = { group = "com.backbase.android.business.journey.contacts-manager-journey", name = "contactsmanager-client-2-contacts-use-case", version.ref = "contacts-manager-journey" }

## F
featureFilterUseCase = { group = "com.backbase.android.retail.feature_filter", name = "feature-filter-use-case", version.ref = "featureFilter" }

## J
journey-test = { group = "com.backbase.android.retail.journey", name = "journey-test", version = "" }

## M
moreMenuJourney = { group = "com.backbase.android.retail.journey", name = "more-journey", version.ref = "moreMenu" }

## R
retail-journey-common = { group = "com.backbase.android.retail.journey", name = "journey-common", version = "" }
retail-journey-common-koin = { group = "com.backbase.android.retail.journey", name = "journey-common-koin", version = "" }

## W
workspaces-journey = { group = "com.backbase.android.business.journey", name = "workspaces-journey", version.ref = "workspaces" }
workspaces-use-case = { group = "com.backbase.android.business.journey.workspaces-journey", name = "accesscontrol-client-2-workspaces-use-case", version.ref = "workspaces" }

[plugins]
## B
base-android-library-module = { id = "base-android-library-module" }

## C
configured-detekt = { id = "configured-detekt" }

## D
dependency-updates = { id = "dependency-updates" }

## F
feature-android-module = { id = "feature-android-module" }

## J
jacoco-codecoverage = { id = "jacoco-codecoverage" }
jacoco-root-codecoverage = { id = "jacoco-root-codecoverage" }

## V
visualiser = { id = "com.backbase.android.visualizer", version = "2.1.0" }

[bundles]
## C
common = [
    "business-journey-common",
    "clients-common-coroutines",
    "retail-journey-common",
    "retail-journey-common-koin",
    "journey-test",
]

## J
journeys = [
    "authentication-journey",
    "moreMenuJourney",
    "contacts-manager-journey",
    "workspaces-journey",
]

## U
useCases = [
    "accessControlEntitlementsUseCase",
    "authentication-use-case",
    "contacts-manager-use-case",
    "featureFilterUseCase",
    "workspaces-use-case",
]
