[versions]

[libraries]
## B
business-journey-common = { group = "com.backbase.android.business.journey", name = "journey-common", version = "9.0.2" }

## C
clients-common-coroutines = { group = "com.backbase.android.clients", name = "clients-common-coroutines", version = "2.0.0" }

## J
journey-test = { group = "com.backbase.android.retail.journey", name = "journey-test", version = "9.0.0" }

## R
retail-journey-common = { group = "com.backbase.android.retail.journey", name = "journey-common", version = "9.0.0" }
retail-journey-common-koin = { group = "com.backbase.android.retail.journey", name = "journey-common-koin", version = "9.0.0" }

[plugins]

[bundles]
## C
common = [
    "business-journey-common",
    "clients-common-coroutines",
    "retail-journey-common",
    "retail-journey-common-koin",
    "journey-test",
]